package by.ld1995tut.Frame;

import by.ld1995tut.Person;
import by.ld1995tut.mics.Number;
import by.ld1995tut.mics.Reg;

import javax.swing.*;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.awt.event.ActionListener;
import java.text.ParseException;

public class FrameNumber {
    private JButton numberButton;
    private JPanel numberPanel;
    private JFormattedTextField numberField;

    public FrameNumber() {
        try {
            MaskFormatter maskFormatter = new MaskFormatter("+### (##) ###-##-##");
            maskFormatter.setPlaceholder(null);
            maskFormatter.setPlaceholderCharacter('.');
            numberField.setFormatterFactory(new DefaultFormatterFactory(maskFormatter));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        if (numberField.getDocument() instanceof AbstractDocument)
            ((AbstractDocument) numberField.getDocument()).setDocumentFilter(new Number());
    }

    //=======================================================

    public JPanel getNumberPanel() {
        return numberPanel;
    }

    public String getNumberField()
    {
        try
        {
            numberField.commitEdit();
            return numberField.getValue().toString();
        }
        catch (ParseException e)
        {
            return null;
        }

    }

    public void addActionListenerForConfirm(ActionListener actionListener) {
        numberButton.addActionListener(actionListener);
        numberField.addActionListener(actionListener);
    }

    public void removeActionListenerForConfirm(ActionListener actionListener) {
        numberButton.removeActionListener(actionListener);
        numberField.removeActionListener(actionListener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        numberPanel = new JPanel();
        numberPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Введите код страны и номер ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        numberPanel.add(label1, gbc);
        numberButton = new JButton();
        numberButton.setHorizontalTextPosition(0);
        numberButton.setMaximumSize(new Dimension(150, 32));
        numberButton.setMinimumSize(new Dimension(150, 32));
        numberButton.setOpaque(true);
        numberButton.setPreferredSize(new Dimension(150, 32));
        numberButton.setText("Продолжить");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        numberPanel.add(numberButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("вашего мобильного телефона");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        numberPanel.add(label2, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        numberPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        numberPanel.add(spacer2, gbc);
        numberField = new JFormattedTextField();
        numberField.setFocusCycleRoot(true);
        numberField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        numberPanel.add(numberField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return numberPanel;
    }
}
