package by.ld1995tut.Frame;

import javax.swing.*;
import java.awt.*;

public class MainForm extends JPanel {
    private JPanel rootPanel;
    private JPanel titlePanel;
    private JPanel listContacts;
    private JPanel messagePanel;

    public MainForm() {
        listContacts.add(new JPanel());
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JPanel getTitlePanel() {
        return titlePanel;
    }

    public void setTitlePanel(JPanel titlePanel) {
        this.titlePanel.add(titlePanel);
    }

    public JPanel getListContacts() {
        return listContacts;
    }

    public void setListContacts(Component contactsPanel) {
        this.listContacts.removeAll();
        this.listContacts.add(contactsPanel);
    }

    public JPanel getMessagePanel() {
        return messagePanel;
    }

    public void setMessagePanel(Component messagesPanel) {
        this.messagePanel.removeAll();
        this.messagePanel.add(messagesPanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        titlePanel = new JPanel();
        titlePanel.setLayout(new GridBagLayout());
        rootPanel.add(titlePanel, BorderLayout.NORTH);
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titlePanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        titlePanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        titlePanel.add(spacer3, gbc);
        listContacts = new JPanel();
        listContacts.setLayout(new BorderLayout(0, 0));
        listContacts.setMinimumSize(new Dimension(350, 0));
        listContacts.setPreferredSize(new Dimension(250, 500));
        rootPanel.add(listContacts, BorderLayout.WEST);
        messagePanel = new JPanel();
        messagePanel.setLayout(new GridBagLayout());
        rootPanel.add(messagePanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
