package by.ld1995tut.Frame;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class MainForm extends JPanel {
    private JPanel rootPanel;
    private JPanel titlePanel;
    private JPanel listContacts;
    private JPanel messagePanel;
    private JPanel searchPanel;
    private JPanel searchIcon;
    private JTextField searchField;
    private JPanel list;

    private BufferedImage search;

    public MainForm() {
        $$$setupUI$$$();
        list.add(new JPanel());
        searchField.setBorder(BorderFactory.createEmptyBorder());
        try {
            search = ImageIO.read(new File("resources/images/icon-search.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JPanel getTitlePanel() {
        return titlePanel;
    }

    public void setTitlePanel(JPanel titlePanel) {
        this.titlePanel.add(titlePanel);
    }

    public JPanel getListContacts() {
        return listContacts;
    }

    public void setList(Component contactsPanel) {
        this.list.removeAll();
        this.list.add(contactsPanel);
    }

    public JPanel getMessagePanel() {
        return messagePanel;
    }

    public void setMessagePanel(Component messagesPanel) {
        this.messagePanel.removeAll();
        this.messagePanel.add(messagesPanel);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        searchIcon = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (search == null) {
                    return;
                }
                g.drawImage(search, 0, 0, null);
            }
        };
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMinimumSize(new Dimension(800, 600));
        rootPanel.setPreferredSize(new Dimension(800, 600));
        titlePanel = new JPanel();
        titlePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titlePanel.setBackground(new Color(-14436636));
        rootPanel.add(titlePanel, BorderLayout.NORTH);
        listContacts = new JPanel();
        listContacts.setLayout(new BorderLayout(0, 0));
        listContacts.setBackground(new Color(-1710619));
        listContacts.setDoubleBuffered(true);
        listContacts.setMinimumSize(new Dimension(230, 500));
        listContacts.setPreferredSize(new Dimension(250, 500));
        rootPanel.add(listContacts, BorderLayout.WEST);
        searchPanel = new JPanel();
        searchPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        searchPanel.setBackground(new Color(-1));
        searchPanel.setPreferredSize(new Dimension(205, 40));
        listContacts.add(searchPanel, BorderLayout.NORTH);
        searchIcon.setMinimumSize(new Dimension(20, 20));
        searchIcon.setOpaque(false);
        searchIcon.setPreferredSize(new Dimension(20, 20));
        searchPanel.add(searchIcon);
        searchField = new JTextField();
        searchField.setFont(new Font("Open Sans", searchField.getFont().getStyle(), 14));
        searchField.setOpaque(false);
        searchField.setPreferredSize(new Dimension(170, 24));
        searchPanel.add(searchField);
        list = new JPanel();
        list.setLayout(new BorderLayout(0, 0));
        list.setBackground(new Color(-4473925));
        listContacts.add(list, BorderLayout.CENTER);
        messagePanel = new JPanel();
        messagePanel.setLayout(new GridBagLayout());
        messagePanel.setBackground(new Color(-1));
        rootPanel.add(messagePanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
