package by.ld1995tut.Contacts;

import org.javagram.dao.Person;
import org.javagram.dao.proxy.TelegramProxy;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;

public class ContactsList extends JPanel {
    private JPanel contactsPanel;
    private JList<Person> list;
    private JScrollPane scrollPanel;
    TelegramProxy telegramProxy;

    public ContactsList() {
        $$$setupUI$$$();


    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        contactsPanel = this;
    }

    public void getContacts(TelegramProxy telegramProxy) {
        this.telegramProxy = telegramProxy;
        java.util.List<Person> dialogs = telegramProxy.getPersons();
        list.setCellRenderer(new ContactsForm(telegramProxy));
        list.setListData(dialogs.toArray(new Person[dialogs.size()]));
    }

    public JPanel getContactsPanel() {
        return contactsPanel;
    }

    public void addListSelectionListener(ListSelectionListener listSelectionListener) {
        list.addListSelectionListener(listSelectionListener);
    }

    public void removeListSelectionListener(ListSelectionListener listSelectionListener) {
        list.removeListSelectionListener(listSelectionListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contactsPanel.setLayout(new BorderLayout(0, 0));
        scrollPanel = new JScrollPane();
        scrollPanel.setBackground(new Color(-1644826));
        scrollPanel.setForeground(new Color(-3223858));
        scrollPanel.setOpaque(false);
        contactsPanel.add(scrollPanel, BorderLayout.CENTER);
        list = new JList();
        list.setBackground(new Color(-1));
        list.setDoubleBuffered(false);
        list.setDragEnabled(false);
        list.setFocusable(true);
        list.setForeground(new Color(-1644826));
        list.setOpaque(false);
        list.setRequestFocusEnabled(true);
        list.setSelectionBackground(new Color(-328961));
        list.setSelectionForeground(new Color(-14436636));
        list.setSelectionMode(2);
        scrollPanel.setViewportView(list);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contactsPanel;
    }
}
