package by.ld1995tut.Contacts;

import org.javagram.dao.Person;
import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;

public class ContactsList extends JPanel {
    private JPanel contactsPanel;
    private JList<Person> list;

    public ContactsList() {

    }

    public void getContacts() {
        list.setCellRenderer(new ContactsForm());
    }

    public JPanel getContactsPanel() {
        return contactsPanel;
    }

    public void addListSelectionListener(ListSelectionListener listSelectionListener) {
        list.addListSelectionListener(listSelectionListener);
    }

    public void removeListSelectionListener(ListSelectionListener listSelectionListener) {
        list.removeListSelectionListener(listSelectionListener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contactsPanel = new JPanel();
        contactsPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        contactsPanel.add(scrollPane1, BorderLayout.CENTER);
        list = new JList();
        scrollPane1.setViewportView(list);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contactsPanel;
    }
}
