package by.ld1995tut;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class FrameWindow {
    private JPanel rootPanel;
    private JButton turn;
    private JButton exit;
    private JPanel systemBoard;
    private JPanel inputPanel;

    public JPanel getInputPanel() {
        return inputPanel;
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JButton getTurn() {
        return turn;
    }

    public JButton getExit() {
        return exit;
    }

    public JPanel getSystemBoard() {
        return systemBoard;
    }

    public void setInputPanel(Component inputPanel) {
        this.inputPanel.removeAll();
        this.inputPanel.add(inputPanel);
        this.inputPanel.validate();
        this.inputPanel.repaint();
    }

    public void addActionListenerForClose(ActionListener listener) {
        exit.addActionListener(listener);
    }

    public void addActionListenerForMinimize(ActionListener listener)
    {
        turn.addActionListener(listener);
    }

    public void removeActionListenerForClose(ActionListener listener) {
        exit.removeActionListener(listener);
    }

    public void removeActionListenerForMinimize(ActionListener listener) {
        turn.removeActionListener(listener);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        systemBoard = new JPanel();
        systemBoard.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        rootPanel.add(systemBoard, BorderLayout.NORTH);
        turn = new JButton();
        turn.setFocusPainted(false);
        turn.setFocusable(false);
        turn.setText("Turn");
        systemBoard.add(turn);
        exit = new JButton();
        exit.setFocusPainted(false);
        exit.setFocusable(false);
        exit.setText("Exit");
        systemBoard.add(exit);
        inputPanel = new JPanel();
        inputPanel.setLayout(new GridBagLayout());
        inputPanel.setMinimumSize(new Dimension(120, 119));
        rootPanel.add(inputPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
