package by.ld1995tut;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class FrameWindow {
    private JPanel rootPanel;
    private JButton turn;
    private JButton exit;
    private JPanel systemBoard;
    private JPanel inputPanel;

    private BufferedImage iconHide;

    public FrameWindow() {
        $$$setupUI$$$();
        try {
            this.iconHide = ImageIO.read(new File("resources/images/icon-hide.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public JPanel getInputPanel() {
        return inputPanel;
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JButton getTurn() {
        return turn;
    }

    public JButton getExit() {
        return exit;
    }

    public JPanel getSystemBoard() {
        return systemBoard;
    }

    public void setInputPanel(Component inputPanel) {
        this.inputPanel.removeAll();
        this.inputPanel.add(inputPanel);
        this.inputPanel.revalidate();
        this.inputPanel.repaint();
    }

    public void addActionListenerForClose(ActionListener listener) {
        exit.addActionListener(listener);
    }

    public void addActionListenerForMinimize(ActionListener listener) {
        turn.addActionListener(listener);
    }

    public void removeActionListenerForClose(ActionListener listener) {
        exit.removeActionListener(listener);
    }

    public void removeActionListenerForMinimize(ActionListener listener) {
        turn.removeActionListener(listener);
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
        turn = new JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(iconHide, 0, 0, null);
            }
        };
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        systemBoard = new JPanel();
        systemBoard.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        rootPanel.add(systemBoard, BorderLayout.NORTH);
        turn.setFocusPainted(false);
        turn.setFocusable(false);
        turn.setText("");
        systemBoard.add(turn);
        exit = new JButton();
        exit.setFocusPainted(false);
        exit.setFocusable(false);
        exit.setText("");
        systemBoard.add(exit);
        inputPanel = new JPanel();
        inputPanel.setLayout(new GridBagLayout());
        inputPanel.setMinimumSize(new Dimension(120, 119));
        rootPanel.add(inputPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
